version: '3'
services:
    # MongoDB: https://hub.docker.com/_/mongo/
    mongo:
      image: mongo:4.2
      restart: always
      volumes:
        - mongo_data:/data/db
    # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
      restart: always
      volumes:
        - es_data:/usr/share/elasticsearch/data
      environment:
        - http.host=0.0.0.0
        - transport.host=localhost
        - network.host=0.0.0.0
        - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms2048m -Xmx2048m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
    # Graylog: https://hub.docker.com/r/graylog/graylog/
    graylog:
      image: graylog/graylog:4.2
      volumes:
        - graylog_data:/usr/share/graylog/data
        # needed to be able to query things like ipam from graylog
        - ./cacerts:/usr/local/openjdk-8/lib/security/cacerts
      environment:
        # CHANGE ME (must be at least 16 characters)!
          GRAYLOG_PASSWORD_SECRET: "passwordpassword"
        # Password: admin
          GRAYLOG_ROOT_PASSWORD_SHA2: "anotherpasswordpassword"
          GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
          VIRTUAL_HOST: "mygrayloghost.example.com"
          VIRTUAL_PORT: "9000"
      entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
      restart: always
      depends_on:
        - mongo
        - elasticsearch
      ports:
        # Graylog web interface and REST API
        - 9000:9000
        # filebeat
        - 5044:5044
        # GELF TCP
        - 12201:12201
        # GELF UDP
        - 12201:12201/udp

    nginx-proxy:
      restart: always
      image: jwilder/nginx-proxy
      volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/gmadmin/certs:/etc/nginx/certs
      ports:
      - 80:80
      - 443:443

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local
